apiVersion: v1
kind: Pod
metadata:
  name: result-app
  labels:
    name: result-app
    app: demo-voting-app
spec:
  containers:   
  - name: result-app
    image: dockersamples/examplevotingapp_result
    ports:
    - containerPort: 80
     